---
all:
  vars:
    ansible_user: sysadmin
    ansible_ssh_pass: "SysAdm2026!"
    ansible_become: true
    ansible_become_password: "SysAdm2026!"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  children:
    ntl_lab:
      hosts:
        dc01:
          ansible_host: 172.16.132.10
        wms-db:
          ansible_host: 172.16.132.20
