---
all:
  children:
    proxmox:
      hosts:
        hv-epyc-02:
          ansible_host: 172.16.60.15
          ansible_connection: local

    windows:
      hosts:
        DC01:
          ansible_host: 192.168.10.10
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore
          ansible_port: 5985
        PC-SIEGE-01:
          ansible_host: 192.168.10.50
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore
          ansible_port: 5985

    linux:
      hosts:
        WMS-DB:
          ansible_host: 192.168.10.21
          ansible_connection: ssh
          ansible_user: sysadmin
          ansible_ssh_pass: "{{ vault_sysadmin_password }}"
          ansible_become: true
          ansible_become_password: "{{ vault_sysadmin_password }}"
