#!/bin/bash
# ==============================================================================
# NTL-SysToolbox — Setup Lab Proxmox (18 VMs, data-driven)
# ==============================================================================
# Reads vms.csv and creates all VMs automatically:
#   - Linux VMs → cloud-init (100% automated)
#   - Windows VMs → autounattend.xml ISO (zero-click install)
#
# Usage:
#   bash setup-lab.sh              # uses config.local.env or config.env
#   bash setup-lab.sh my-config.env
#
# Prerequisites:
#   - Run as root on the Proxmox host
#   - ISOs/cloud images downloaded (run download-images.sh first)
#   - genisoimage installed (for Windows autounattend ISOs)
# ==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# --- Load config ---
CONFIG_FILE="${1:-}"
if [[ -z "$CONFIG_FILE" ]]; then
    if [[ -f "$SCRIPT_DIR/config.local.env" ]]; then
        CONFIG_FILE="$SCRIPT_DIR/config.local.env"
    else
        CONFIG_FILE="$SCRIPT_DIR/config.env"
    fi
fi

if [[ ! -f "$CONFIG_FILE" ]]; then
    echo "ERREUR: Config introuvable: $CONFIG_FILE"
    echo "Copiez config.env vers config.local.env et remplissez vos valeurs."
    exit 1
fi

# shellcheck source=config.env
source "$CONFIG_FILE"

# --- Source lib ---
source "$SCRIPT_DIR/lib/common.sh"
source "$SCRIPT_DIR/lib/create-linux-vm.sh"
source "$SCRIPT_DIR/lib/create-windows-vm.sh"

# --- Paths ---
VMS_CSV="$SCRIPT_DIR/vms.csv"
IMAGES_CONF="$SCRIPT_DIR/images.conf"
export IMAGES_CONF SCRIPT_DIR

# Derive DNS server from vms.csv (first DC = DC01)
DNS_SERVER=$(get_dns_server "$VMS_CSV" "$SUBNET")
export DNS_SERVER

# ==============================================================================
# PRE-FLIGHT CHECKS
# ==============================================================================
step "Pre-flight checks"

if [[ "$(id -u)" -ne 0 ]]; then
    err "Ce script doit etre execute en root sur le Proxmox host."
    exit 1
fi

if ! command -v qm &>/dev/null; then
    err "qm introuvable. Executez ceci sur un Proxmox VE."
    exit 1
fi

if [[ ! -f "$VMS_CSV" ]]; then
    err "vms.csv introuvable: $VMS_CSV"
    exit 1
fi

if [[ ! -f "$IMAGES_CONF" ]]; then
    err "images.conf introuvable: $IMAGES_CONF"
    exit 1
fi

# Check storage
if ! pvesm status | grep -q "^${STORAGE}"; then
    err "Storage '$STORAGE' introuvable."
    pvesm status
    exit 1
fi
log "Storage '$STORAGE' OK"

# Check for VMID conflicts
CONFLICTS=0
check_vmid_conflict() {
    local vmid="$1" hostname="$2"
    shift 7
    if vm_exists "$vmid"; then
        err "VM ID $vmid ($hostname) deja utilisee !"
        CONFLICTS=$((CONFLICTS + 1))
    fi
}
parse_vms "$VMS_CSV" check_vmid_conflict
if [[ $CONFLICTS -gt 0 ]]; then
    err "$CONFLICTS conflits de VM ID. Modifiez vms.csv ou supprimez les VMs existantes."
    exit 1
fi
log "Aucun conflit de VM IDs"

# Check genisoimage for Windows VMs
if ! command -v genisoimage &>/dev/null && ! command -v mkisofs &>/dev/null; then
    warn "genisoimage/mkisofs non installe. Les ISOs autounattend ne pourront pas etre creees."
    warn "Installez: apt install genisoimage"
fi

# Count VMs
TOTAL_LINUX=0
TOTAL_WINDOWS=0
count_vms() {
    local os_key="$3"
    local vm_type
    vm_type=$(get_image_type "$os_key" "$IMAGES_CONF")
    if [[ "$vm_type" == "linux" ]]; then
        TOTAL_LINUX=$((TOTAL_LINUX + 1))
    else
        TOTAL_WINDOWS=$((TOTAL_WINDOWS + 1))
    fi
}
parse_vms "$VMS_CSV" count_vms
log "VMs a creer: $TOTAL_LINUX Linux + $TOTAL_WINDOWS Windows = $((TOTAL_LINUX + TOTAL_WINDOWS)) total"

echo ""
echo "=== NTL-SysToolbox — Setup Lab (${TOTAL_LINUX} Linux + ${TOTAL_WINDOWS} Windows) ==="
echo "Config : $CONFIG_FILE"
echo "Reseau : ${SUBNET}.0/${CIDR} sur ${BRIDGE}"
echo "DNS    : $DNS_SERVER (DC01)"
echo ""

# ==============================================================================
# PHASE 1 — NETWORK
# ==============================================================================
step "Phase 1 — Configuration reseau (bridge $BRIDGE)"

if grep -q "iface ${BRIDGE}" /etc/network/interfaces 2>/dev/null; then
    warn "Bridge $BRIDGE existe deja, on le garde."
else
    echo "Creation du bridge $BRIDGE (${GATEWAY}/${CIDR})..."

    cat >> /etc/network/interfaces << EOF

# NTL Lab Network — Auto-generated by setup-lab.sh
auto ${BRIDGE}
iface ${BRIDGE} inet static
    address ${GATEWAY}/${CIDR}
    bridge-ports none
    bridge-stp off
    bridge-fd 0
EOF

    if [[ "$ENABLE_NAT" == "yes" ]]; then
        cat >> /etc/network/interfaces << EOF
    post-up   iptables -t nat -A POSTROUTING -s ${SUBNET}.0/${CIDR} -o ${NAT_INTERFACE} -j MASQUERADE
    post-down iptables -t nat -D POSTROUTING -s ${SUBNET}.0/${CIDR} -o ${NAT_INTERFACE} -j MASQUERADE
EOF
    fi

    run_cmd ifup "${BRIDGE}" 2>/dev/null || ifreload -a
    log "Bridge $BRIDGE cree et actif"
fi

# IP forwarding
if [[ "$ENABLE_NAT" == "yes" ]]; then
    if ! sysctl net.ipv4.ip_forward | grep -q "= 1"; then
        echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
        sysctl -w net.ipv4.ip_forward=1 > /dev/null
        log "IP forwarding active"
    else
        log "IP forwarding deja actif"
    fi
fi

# ==============================================================================
# PHASE 2 — CREATE ALL VMs
# ==============================================================================
step "Phase 2 — Creation des VMs"

# Work directory for generated files
mkdir -p "$WORK_DIR"

CREATED_LINUX=0
CREATED_WINDOWS=0
FAILED=0

create_vm_from_csv() {
    local vmid="$1" hostname="$2" os_key="$3" ip_suffix="$4"
    local cores="$5" ram="$6" disk="$7" post_install="$8"

    local vm_type
    vm_type=$(get_image_type "$os_key" "$IMAGES_CONF")

    echo ""
    if [[ "$vm_type" == "linux" ]]; then
        if create_linux_vm "$vmid" "$hostname" "$os_key" "$ip_suffix" \
                           "$cores" "$ram" "$disk" "$post_install"; then
            CREATED_LINUX=$((CREATED_LINUX + 1))
        else
            err "Echec creation VM $vmid ($hostname)"
            FAILED=$((FAILED + 1))
        fi
    elif [[ "$vm_type" == "windows" ]]; then
        if create_windows_vm "$vmid" "$hostname" "$os_key" "$ip_suffix" \
                             "$cores" "$ram" "$disk" "$post_install"; then
            CREATED_WINDOWS=$((CREATED_WINDOWS + 1))
        else
            err "Echec creation VM $vmid ($hostname)"
            FAILED=$((FAILED + 1))
        fi
    else
        err "Type inconnu pour $os_key: $vm_type"
        FAILED=$((FAILED + 1))
    fi
}

parse_vms "$VMS_CSV" create_vm_from_csv

# ==============================================================================
# PHASE 3 — SNAPSHOTS
# ==============================================================================
if [[ "$AUTO_SNAPSHOT" == "yes" ]]; then
    step "Phase 3 — Snapshots (Linux VMs)"

    snapshot_linux_vm() {
        local vmid="$1" hostname="$2" os_key="$3"
        shift 7
        local vm_type
        vm_type=$(get_image_type "$os_key" "$IMAGES_CONF")
        [[ "$vm_type" != "linux" ]] && return 0

        if qm status "$vmid" 2>/dev/null | grep -q "running"; then
            echo "  Attente cloud-init VM $vmid ($hostname)..."
            for _ in $(seq 1 30); do
                if qm guest exec "$vmid" -- test -f /var/lib/cloud/instance/boot-finished 2>/dev/null; then
                    break
                fi
                sleep 10
            done
            run_cmd qm snapshot "$vmid" clean-state --description "NTL Lab — config initiale"
            log "  Snapshot 'clean-state' pour VM $vmid ($hostname)"
        fi
    }

    parse_vms "$VMS_CSV" snapshot_linux_vm

    echo ""
    echo "Pour les VMs Windows, les snapshots seront crees apres l'install automatique."
    echo "Comptez ~30-60 min pour l'install Windows + post-install."
    echo "Verifiez ensuite avec: qm list | grep -E '10[0-9]{2}'"
fi

# ==============================================================================
# PHASE 4 — VERIFICATION
# ==============================================================================
step "Phase 4 — Verification"

echo ""
echo "Tests de connectivite (apres quelques minutes de boot)..."
echo ""

verify_vm() {
    local vmid="$1" hostname="$2" os_key="$3" ip_suffix="$4"
    shift 4; shift 3; shift
    local ip="${SUBNET}.${ip_suffix}"
    if ping -c 1 -W 2 "$ip" &>/dev/null; then
        log "  $hostname ($ip) — reachable"
    else
        warn "  $hostname ($ip) — not yet reachable (may still be booting)"
    fi
}

parse_vms "$VMS_CSV" verify_vm

# Quick service checks
echo ""
echo "Tests de services (si les VMs sont pretes)..."
# AD/LDAP on DC01
DC01_IP="${SUBNET}.10"
if timeout 2 bash -c "echo > /dev/tcp/${DC01_IP}/389" 2>/dev/null; then
    log "  LDAP (389) on DC01 ($DC01_IP) — OK"
else
    warn "  LDAP (389) on DC01 ($DC01_IP) — not ready"
fi

# MySQL on WMS-DB
WMSDB_IP="${SUBNET}.21"
if timeout 2 bash -c "echo > /dev/tcp/${WMSDB_IP}/3306" 2>/dev/null; then
    log "  MySQL (3306) on WMS-DB ($WMSDB_IP) — OK"
else
    warn "  MySQL (3306) on WMS-DB ($WMSDB_IP) — not ready"
fi

# SSH on WMS-DB
if timeout 2 bash -c "echo > /dev/tcp/${WMSDB_IP}/22" 2>/dev/null; then
    log "  SSH (22) on WMS-DB ($WMSDB_IP) — OK"
else
    warn "  SSH (22) on WMS-DB ($WMSDB_IP) — not ready"
fi

# ==============================================================================
# SUMMARY
# ==============================================================================
step "Resume du lab"

echo ""
printf "%-7s %-15s %-22s %-18s %s\n" "VMID" "Hostname" "OS" "IP" "Type"
printf "%-7s %-15s %-22s %-18s %s\n" "-----" "--------" "--" "--" "----"

print_summary() {
    local vmid="$1" hostname="$2" os_key="$3" ip_suffix="$4"
    shift 4; shift 3; shift
    local ip="${SUBNET}.${ip_suffix}"
    local vm_type
    vm_type=$(get_image_type "$os_key" "$IMAGES_CONF")
    local status="cloud-init"
    [[ "$vm_type" == "windows" ]] && status="autounattend"
    printf "%-7s %-15s %-22s %-18s %s\n" "$vmid" "$hostname" "$os_key" "$ip" "$status"
}

parse_vms "$VMS_CSV" print_summary

echo ""
echo "Reseau  : ${SUBNET}.0/${CIDR} sur bridge ${BRIDGE}"
echo "Gateway : ${GATEWAY}"
echo "DNS     : ${DNS_SERVER}"
echo "NAT     : ${ENABLE_NAT} (via ${NAT_INTERFACE})"
echo ""
echo "Crees   : $CREATED_LINUX Linux + $CREATED_WINDOWS Windows"
[[ $FAILED -gt 0 ]] && err "Echecs  : $FAILED"
echo ""
echo "Credentials Linux  : ${LINUX_USER} / ${LINUX_PASSWORD}"
echo "Credentials Windows: Administrator / ${WINDOWS_ADMIN_PASSWORD}"
echo "AD Domain          : ${AD_DOMAIN}"
echo ""
echo "=== Setup termine ==="
